server:
    verbosity: 1
    interface: 0.0.0.0
    interface: 0.0.0.0@8443
    port: 53
    https-port: 8443

    username: ""
    chroot: ""
    directory: "/config"
    pidfile: ""

    use-syslog: no
    logfile: ""

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    access-control: 172.18.0.0/16 allow

    num-threads: 1
    module-config: "validator iterator"

    prefetch: no
    serve-expired: no
    cache-min-ttl: 0
    cache-max-ttl: 86400

    harden-dnssec-stripped: yes
    local-zone: "test." nodefault
    trust-anchor-file: "/config/trust-anchor.key"

    tls-service-key: "/config/doh.key"
    tls-service-pem: "/config/doh.crt"

forward-zone:
    name: "service.test."
    forward-addr: 172.18.0.54@53
    forward-first: no
